### ISSUE TITLE
Use best practice TLS settings for all Bisq block explorers

### ISSUE THREAD

**Issue by wiz** [bisq-network/ops#10]
Everyone should get an A+ score on the SSL Labs test:

@wiz 
- [X] https://www.ssllabs.com/ssltest/analyze.html?d=mempool.space&s=2401%3ab140%3a0%3a0%3a0%3a0%3a42%3a100
- [X] https://www.ssllabs.com/ssltest/analyze.html?d=explorer.monero.wiz.biz&s=103.99.170.77

@devinbileck 
- [X] https://www.ssllabs.com/ssltest/analyze.html?d=mempool.bisq.services
- [x] https://www.ssllabs.com/ssltest/analyze.html?d=xmrblocks.bisq.services

@emzy 
- [x] https://www.ssllabs.com/ssltest/analyze.html?d=mempool.emzy.de&s=95.216.6.156&latest
- [x] https://www.ssllabs.com/ssltest/analyze.html?d=xmrblocks.monero.emzy.de&s=2a01%3a4f8%3a192%3a628a%3a0%3a0%3a0%3a90&latest

**Comment by Emzy** [comment]
Done. Both A+

**Comment by devinbileck** [comment]
Done. Both of mine are also A+.
