### ISSUE TITLE
Upgrade all Bitcoin nodes to Tor v3 onions

### ISSUE THREAD

**Issue by wiz** [bisq-network/ops#11]
Migration plan TBD after Bisq implements support for Bitcoin Nodes with V3 onions, which currently doesn't work for some reason inside bitcoinj.

Current list of V2 onion Bitcoin Nodes in Bisq v1.4.0:

- [ ] `m3yqzythryowgedc` (@wiz)
- [ ] `jiuuuislm7ooesic` (@wiz)
- [ ] `orsy2v63ecrmdj55` (@wiz)
- [ ] `z6mbqq7llxlrn4kq` (@wiz)
- [ ] `fz6nsij6jiyuwlsc` (@emzy)
- [ ] `c6ac4jdfyeiakex2` (@emzy)
- [ ] `sjyzmwwu6diiit3r` (@emzy)
- [ ] `3xucqntxp5ddoaz5` (@emzy)
- [ ] `4jyh6llqj264oggs` (@miker)
- [ ] `mxdtrjhe2yfsx3pg` (@miker)
- [ ] `lva54pnbq2nsmjyr` (@devinbileck)
- [ ] `qxjrxmhyqp5vy5hj` (@devinbileck)
- [ ] `lgkvbvro67jomosw` (@Christoph)
- [ ] `3r44ddzjitznyahw` (@sqrrm)
- [ ] `i3a5xtzfm4xwtybd` (@sqrrm)
- [ ] `mbm6ffx6j5ygi2ck` (@KanoczTomas)
- [ ] `4nnuyxm5k5tlyjq3` (@m52go)
- [ ] `2pj2o2mrawj7yotg` (@robkaandorp)

Experimental V3 onion nodes:
* `wizbit5555bsslwv4ctronnsgk5vh2w2pdx7v7eyuivlyuoteejk7lid` (@wiz)

**Comment by Emzy** [comment]
All done.
