### ISSUE TITLE
Upgrade all Bisq Seednodes to Tor V3 onions

### ISSUE THREAD

**Issue by wiz** [bisq-network/ops#4]
As part of the ongoing https://github.com/bisq-network/projects/issues/23 to upgrade Bisq to using Tor V3, we need to upgrade all 12 seednodes to use V3 onions:

Retirement V2 list, removed from master, currently in retirement period:

- [ ] `5quyxpxheyvzmb2d` (@mrosseel) [removed](https://github.com/bisq-network/bisq/pull/4645) in October 2020, to be shut down after v1.5.2 release
- [ ] `rm7b56wbrcczpjvl` (@mrosseel) [removed](https://github.com/bisq-network/bisq/pull/4645) in October 2020, to be shut down after v1.5.2 release
- [ ] `s67qglwhkgkyvr74` (@emzy) [removed](https://github.com/bisq-network/bisq/pull/4644) in October 2020, to be shut down after v1.5.3 release
- [ ] `723ljisnynbtdohi` (@emzy) [removed](https://github.com/bisq-network/bisq/pull/4644) in October 2020, to be shut down after v1.5.3 release

Shut down V2 list, removed from master, was shut down:

- [X] `jhgcy2won7xnslrb` (@wiz) [removed](https://github.com/bisq-network/bisq/pull/4113) April 2020, was shut down July 2020
- [X] `ef5qnzx6znifo3df` (@wiz) [removed](https://github.com/bisq-network/bisq/pull/4302) June 2020, was shut down August 2020
- [X] `fl3mmribyxgrv63c` (@devinbileck) [removed](https://github.com/bisq-network/bisq/pull/4408) in August 2020, shut down November 2020
- [X] `3f3cu2yw7u457ztq` (@devinbileck) [removed](https://github.com/bisq-network/bisq/pull/4408) in August 2020, shut down November 2020

Active V3 list in production:

* `sn3bsq3evqkpshdmc3sbdxafkhfnk7ctop44jsxbxyys5ridsaw5abyd` (@mrosseel) [added](https://github.com/bisq-network/bisq/pull/4645) October 2020 `v1.4.0`
* `sn4bsqpc7eb2ntvpsycxbzqt6fre72l4krp2fl5svphfh2eusrqtq3qd` (@mrosseel) [added](https://github.com/bisq-network/bisq/pull/4645) October 2020 `v1.4.0`
* `sn4emzywye3dhjouv7jig677qepg7fnusjidw74fbwneieruhmi7fuyd ` (@emzy) [added](https://github.com/bisq-network/bisq/pull/4644) October 2020 `v1.4.0`
* `sn5emzyvxuildv34n6jewfp2zeota4aq63fsl5yyilnvksezr3htveqd ` (@emzy) [added](https://github.com/bisq-network/bisq/pull/4644) October 2020 `v1.4.0`
* `devinv3rhon24gqf5v6ondoqgyrbzyqihzyouzv7ptltsewhfmox2zqd` (@devinbileck) [added](https://github.com/bisq-network/bisq/pull/4408) August 2020 `v1.3.8`
* `devinsn2teu33efff62bnvwbxmfgbfjlgqsu3ad4b4fudx3a725eqnyd` (@devinbileck) [added](https://github.com/bisq-network/bisq/pull/4408) August 2020 `v1.3.8`
* `sn2bisqad7ncazupgbd3dcedqh5ptirgwofw63djwpdtftwhddo75oid` (@mrosseel) [added](https://github.com/bisq-network/bisq/pull/4352) July 2020 `v1.3.7`
* `sn3emzy56u3mxzsr4geysc52feoq5qt7ja56km6gygwnszkshunn2sid` (@emzy) [added](https://github.com/bisq-network/bisq/pull/4332) June 2020 `v1.3.6`
* `devinsn3xuzxhj6pmammrxpydhwwmwp75qkksedo5dn2tlmu7jggo7id` (@devinbileck) [added](https://github.com/bisq-network/bisq/pull/4320) July 2020 `v1.3.6`
* `wizseed3d376esppbmbjxk2fhk2jg5fpucddrzj2kxtbxbx4vrnwclad` (@wiz) [added](https://github.com/bisq-network/bisq/pull/4302) June 2020 `v1.3.6`
* `wizseed7ab2gi3x267xahrp2pkndyrovczezzb46jk6quvguciuyqrid` (@wiz) [added](https://github.com/bisq-network/bisq/pull/4302) June 2020 `v1.3.6`
* `wizseedscybbttk4bmb2lzvbuk2jtect37lcpva4l3twktmkzemwbead` (@wiz) [added](https://github.com/bisq-network/bisq/pull/4113) April 2020 `v1.3.2`

The migration procedure is essentially:

* Create new V3 seednode, optionally with vanity address to help identification
* Merge PR to replace V2 hostname with V3 hostname
* Keep both instances running for 3 months during transition period while old users upgrade
* After 3 months, shut down old V2 node

**Comment by wiz** [comment]
@devinbileck Thanks, please keep `fl3mmribyxgrv63c` and `3f3cu2yw7u457ztq` running until November 2020

**Comment by wiz** [comment]
@emzy @mrosseel can you guys setup new v3 seednodes in time for the v1.4.0 release?

**Comment by Emzy** [comment]
Two fresh seednodes:
sn4emzywye3dhjouv7jig677qepg7fnusjidw74fbwneieruhmi7fuyd.onion
sn5emzyvxuildv34n6jewfp2zeota4aq63fsl5yyilnvksezr3htveqd.onion

**Comment by Emzy** [comment]
All are removed
