### ISSUE TITLE
Enable DNSSEC for all Bisq infrastructure domain names

### ISSUE THREAD

**Issue by wiz** [bisq-network/ops#7]
- [x] bisq.network https://dnsviz.net/d/bisq.network/dnssec/
- [x] bisq.io https://dnsviz.net/d/bisq.io/dnssec/
- [x] bisq.community https://dnsviz.net/d/bisq.community/dnssec/
- [x] bisq.wiki https://dnsviz.net/d/bisq.wiki/dnssec/
- [x] bisq.market https://dnsviz.net/d/bisq.market/dnssec/
- [x] bisq.markets https://dnsviz.net/d/bisq.markets/dnssec/
- [X] mempool.space https://dnsviz.net/d/mempool.space/dnssec/
- [X] wiz.biz https://dnsviz.net/d/wiz.biz/dnssec/
- [x] emzy.de https://dnsviz.net/d/emzy.de/dnssec/
- [x] bisq.services https://dnsviz.net/d/bisq.services/dnssec/
- [ ] bisq.cc https://dnsviz.net/d/bisq.cc/dnssec/
- [ ] vante.me https://dnsviz.net/d/vante.me/dnssec/
- [x] sqrrm.net https://dnsviz.net/d/sqrrm.net/dnssec/

**Comment by cbeams** [comment]
From https://support.cloudflare.com/hc/en-us/articles/360006660072-Understanding-and-Configuring-DNSSEC-in-Cloudflare-DNS:

> To configure DNSSEC, you first enable it in the Cloudflare dashboard and then add a DS record at your domain registrar.

I'll do this for all the domains above that are managed under Cloudflare DNS. I'll then assign @ManfredKarrer to take care of the domain registrar part, as he plays the role of Domain Name Owner (bisq-network/roles#77) and is now the only one with access to make such changes.

**Comment by devinbileck** [comment]
I have enabled DNSSEC on the bisq.services domain.

**Comment by cbeams** [comment]
Attn @ManfredKarrer: I have just enabled DNSSEC for the bisq.network domain via Cloudflare DNS. You now need to follow the instructions at https://www.namecheap.com/support/knowledgebase/article.aspx/9722/2232/managing-dnssec-for-domains-pointed-to-custom-dns to register the values below with Namecheap. A screenshot from the Cloudflare interface follows, with each of the individual values pasted below.

<img width="523" alt="image" src="https://user-images.githubusercontent.com/301810/90600223-74712d00-e1f6-11ea-8a00-8eec0f2479a9.png">

### DS Record
bisq.network. 3600 IN DS 2371 13 2 29A0443DC8173F7C3A57E58645C0E10FDD0E4B757CDB276020D9AFCBE79F52CD

### Digest
29A0443DC8173F7C3A57E58645C0E10FDD0E4B757CDB276020D9AFCBE79F52CD

### Digest Type
SHA256

### Algorithm
13

### Public Key
mdsswUyr3DPW132mOi8V9xESWE8jTo0dxCjjnopKl+GqJxpVXckHAeF+KkxLbxILfDLUT0rAK9iUzy1L53eKGQ==

### Key Tag
2371

### Flags
257 (KSK)

**Comment by chimp1984** [comment]
@cbeams Thanks. Done.

**Comment by ManfredKarrer** [comment]
Done.

**Comment by wiz** [comment]
@ManfredKarrer looks great, just verified it. thank you!

**Comment by ManfredKarrer** [comment]
Also done now for bisq.io.

**Comment by alexej996** [comment]
bisq.community has dnssec enabled now. Sorry for the delay, had to change the domain provider.

**Comment by Emzy** [comment]
emzy.de has dnssec now.

**Comment by wiz** [comment]
Since the last 3 explorers are the ones that don't have DNSSEC, closing per https://github.com/bisq-network/bisq/pull/4791

**Comment by sqrrm** [comment]
Finally enabled dnssec for sqrrm.net, thanks for the reminder.

**Comment by wiz** [comment]
Okay cool... Well, I checked your checkbox, but your legacy BSQ explorer is still retired :)

**Comment by sqrrm** [comment]
Yeah, I think I will stop running an explorer. I don't think we need that many and getting mempool up and running, and then keeping it stable, is better left for those of you with more ops experience.

I'll keep running the bitcoin nodes.
